version: '3.8'

services:
jenkins:
    user: "1000:1000"
  frontend:
    build:
      context: .
      dockerfile: FrontDockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: BackDockerfile
    ports:
      - "8080:8080"
